### PR TITLE
Update line layout

### PR DESCRIPTION
**Pull request by nickh**
- Resize the `chord-list` td based on the number of chords listed
- Handle chord changes inside a word, drop the break between letters

/cc @jglovier making sure this isn't stepping on any of your design :heart: changes

### CODE REVIEW

**Comment by jglovier** [comment]
:+1: @nickh I'd like to work on the chord-list some, but feel free to merge this in. Won't have any time to do that for a few days.

**Comment by jglovier** [comment]
...or maybe I should merge mine in first since it has some structural changes?

**Comment by jglovier** [comment]
...actually after viewing the diff, it shouldn't present any conflicts with my branch.

**Comment by nickh** [comment]
:cool: thanks

**Pull request merged**
