### PR TITLE
Design love [WIP]

### PR DESCRIPTION
**Pull request by jglovier**
Some :lipstick: things.

### CODE REVIEW

**Comment by jglovier** [comment]
Some site header initial styles:

image

**Comment by nickh** [comment]
Oh man that looks SO MUCH BETTER

:heart: the svg logo

**Comment by nickh** [comment]
Is this still IP or at a state where I can merge it? It looks way better than the current lack-of-design.

**Comment by jglovier** [comment]
Oh sure - technically it's IP, but I've not had a chance to get back to it so feel free to merge and I'll open another when I get back to it. :+1:

**Pull request merged**
